
export type Country = {
"name": object,
"tld": Array<string>,
"cca2": string,
"ccn3": string,
"cca3": string,
"cioc": string,
"independent": boolean,
"status": string,
"unMember": boolean,
"currencies": object,
"idd": object,
"capital": Array<string>,
"altSpellings": Array<string>,
"region": "Africa" | "Americas" | "Asia" | "Europe" | "Oceania",
"subregion": string,
"languages": object,
"translations": object,
"latlng": Array<number>,
"landlocked": boolean,
"borders": Array<string>,
"area": number,
"demonyms": object,
"flag": string,
"maps": object,
"population": number,
"gini": object,
"fifa": string,
"car": object,
"timezones":  Array<string>,
"continents": Array<string>,
"flags": Array<string>,
"coatOfArms": Array<string>,
"startOfWeek": string,
"capitalInfo": object,
};
